# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a8a3d31d57201c2ce65093e8eaa0352ca9ed9cc1f7dcea68ea9c19133b850fdce385cecf5de5f4285765726078c5fe421b949e654d1123c86c4c121fdc09bc

test:
  secret_key_base: 185e7a7e2cc457842593bbed275e40dc1e50bd9e6302cf19d0863b2515279eb26fe6391bb5d96ac9e83c8d4e8deed42d8a808fcd62b0e8c264edfea183afc0f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
